---
author: ~
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jifty-Plugin-Authentication-Ldap
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Jifty: 0
  Net::LDAP: 0
version: undef
